from Triee import *

T=Trie()
print("Ejercicio_1-------------------------")
insert(T,"cris")
insert(T,"cruz")
insert(T,"javi")
insert(T,"juan")
insert(T,"rafa")
all_words = get_all_words(T)
print(all_words)
print("buscar 'cris'",search(T,"cris"))
print("buscar 'cruz'",search(T,"cruz"))
print("buscar 'javi'",search(T,"javi"))
print("buscar 'juan'",search(T,"juan"))
print("buscar 'rafa'",search(T,"rafa"))
print("Ejercio_3-------------------------")
#A=delete(T,"cris")
#print("delete 'cris':",A)
#all_words = get_all_words(T)
#print(all_words)
print("Ejercio_4-------------------------")
B=prefj(T,"j",4)
print(B)
print("Ejercio_5-------------------------")
T1=Trie()
insert(T1,"rafa")
insert(T1,"javi")
insert(T1,"cris")
insert(T1,"cruz")
all_words =get_all_words(T1)
print(all_words)
A=compare_tries(T1,T)
print(A)

print("Ejercio_6-------------------------")
insert(T1,"afar")
all_words =get_all_words(T1)
print(all_words)
print(is_inverted_pair(T1))
print("Ejercio_7-------------------------")
