from Graph import *
print("Vertices y Aristas:")
V=LinkedList()
V.insert(0)
V.insert(1)
V.insert(2)
V.insert(3)
V.insert(5)
V.display()

A=LinkedList()
A.insert((0,1))
A.insert((1,2))
A.insert((1,3))
A.insert((3,5))
A.display()
print('\n',"Grafo:")
graph=createGraph(V,A)
display_graph(graph)
print('\n',f"Exite un camino entre los nodos {1} y {5} :",existPath(graph,1,5))
print('\n',"Es conexo :",isConnected(graph))
print('\n',"Vertices y arista")
A.insert((0,2)),A.insert((0,3)),A.insert((0,5))
A.insert((1,5))
A.insert((2,3)),A.insert((2,5))
V.display()
A.display()
print('\n',"Grafo")
graph_2=createGraph(V,A)
display_graph(graph_2)
print("Es completo :",isComplete(graph_2))

